services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duky-store-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-4000}:4000"
